services:
  database:
    image: "postgres:16.0-alpine3.18"
    env_file:
      - .env.development
    ports:
      - "9432:5432"
    networks:
    - postgres-compose-network
  pgAdmin:
    image: dpage/pgadmin4
    env_file:
      - .env.development
    ports:
      - "1650:80"
    depends_on:
      - database
    networks:
      - postgres-compose-network
networks:
  postgres-compose-network:
    driver: bridge
